<a href="https://colab.research.google.com/github/tianygoulart/Machine-Leaning/blob/main/Desafiomodulo2ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df=df.dropna()
X=df.drop('label', axis=1)
y=df['label']

In [5]:
X.shape

(18285, 4)

In [6]:
y.shape

(18285,)

In [7]:
import tensorflow as tf

In [8]:
tf.__version__

'2.8.0'

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [10]:
voc_size=5000

In [11]:
messages=X.copy()

In [12]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [13]:
messages.reset_index(inplace=True)

In [14]:
import nltk
import re
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [15]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('^a-zA-Z', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

A saída de streaming foi truncada nas últimas 5000 linhas.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441

In [16]:
print(corpus)

['hous dem aide: didn’t even see comey’ letter jason chaffetz tweet', 'flynn: hillari clinton, big woman campu - breitbart', 'truth might get fire', '15 civilian kill singl us airstrik identifi', 'iranian woman jail fiction unpublish stori woman stone death adulteri', 'jacki mason: hollywood would love trump bomb north korea lack tran bathroom (exclus video) - breitbart', 'benoît hamon win french socialist party’ presidenti nomin - new york time', 'back-channel plan ukrain russia, courtesi trump associ - new york time', 'obama’ organ action partner soros-link ‘indivisible’ disrupt trump’ agenda', 'bbc comedi sketch "real housew isis" caus outrag', 'russian research discov secret nazi militari base ‘treasur hunter’ arctic [photos]', 'us offici see link trump russia', 're: yes, paid govern troll social media, blogs, forum websit', 'major leagu soccer, argentin find home success - new york time', 'well fargo chief abruptli step - new york time', 'anonym donor pay $2.5 million releas every

In [17]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2667, 2407, 3575, 2451, 4991, 4987, 4275, 2357, 3907, 1581, 317],
 [2434, 2275, 4617, 2548, 2394, 4002, 2146],
 [2461, 4416, 3201, 1753],
 [2201, 3122, 3025, 2630, 2054, 1037, 4912],
 [3297, 2394, 395, 1323, 2089, 2434, 2394, 1319, 3930, 4244],
 [4728,
  249,
  3744,
  3777,
  3345,
  4416,
  3775,
  1688,
  94,
  1547,
  4961,
  4420,
  3207,
  3782,
  2146],
 [4687, 4764, 2980, 3576, 2683, 1946, 2745, 2860, 281, 3015, 4010],
 [558, 4315, 314, 2507, 1336, 1796, 4416, 4810, 281, 3015, 4010],
 [3425, 855, 4819, 2097, 3740, 3830, 4573, 2676, 4400, 1454],
 [574, 1011, 3958, 276, 3174, 2184, 3480, 863],
 [2394, 863, 3978, 431, 3057, 4470, 1700, 4434, 4962, 2246, 1620],
 [2054, 4497, 4987, 3830, 4416, 1336],
 [3786, 180, 3427, 3187, 15, 4932, 2811, 1793, 2026, 1696],
 [4074, 83, 2823, 2483, 3367, 1331, 4307, 281, 3015, 4010],
 [1764, 4916, 1329, 2486, 1892, 281, 3015, 4010],
 [1646, 2689, 1880, 2189, 2128, 4361, 1206, 3817, 3004, 541, 1104, 1547],
 [431, 3182, 1877],
 [4823, 2947, 2590, 7

In [18]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3907 1581  317]
 [   0    0    0 ... 2394 4002 2146]
 [   0    0    0 ... 4416 3201 1753]
 ...
 [   0    0    0 ...  281 3015 4010]
 [   0    0    0 ...  732   39 3533]
 [   0    0    0 ... 4484 4389 4538]]


In [49]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0, 2667, 2407,
       3575, 2451, 4991, 4987, 4275, 2357, 3907, 1581,  317], dtype=int32)

In [50]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='SGD',metrics=['accuracy'])
print(model.summary())

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_7 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_7 (LSTM)               (None, 100)               56400     
                                                                 
 dense_7 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [56]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_8 (LSTM)               (None, 100)               56400     
                                                                 
 dense_8 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [42]:
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='tanh'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 20, 40)            200000    
                                                                 
 lstm_5 (LSTM)               (None, 100)               56400     
                                                                 
 dense_5 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [43]:
embedding_vector_features=40
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(Bidirectional(LSTM(100)))
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_6 (Embedding)     (None, 20, 40)            200000    
                                                                 
 bidirectional_1 (Bidirectio  (None, 200)              112800    
 nal)                                                            
                                                                 
 dropout_1 (Dropout)         (None, 200)               0         
                                                                 
 dense_6 (Dense)             (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [57]:
len(embedded_docs), y.shape

(18285, (18285,))

In [58]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y) 

In [59]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.15, random_state=42)
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(15542, 20) (15542,)
(2743, 20) (2743,)


In [62]:
train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)
#train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)
#train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Epoch 1/10
243/243 [==============================] - 11s 36ms/step - loss: 0.3000 - accuracy: 0.8608 - val_loss: 0.1996 - val_accuracy: 0.9063
Epoch 2/10
243/243 [==============================] - 9s 38ms/step - loss: 0.1342 - accuracy: 0.9504 - val_loss: 0.2131 - val_accuracy: 0.9089
Epoch 3/10
243/243 [==============================] - 10s 39ms/step - loss: 0.0925 - accuracy: 0.9649 - val_loss: 0.2260 - val_accuracy: 0.9089
Epoch 4/10
243/243 [==============================] - 10s 40ms/step - loss: 0.0589 - accuracy: 0.9798 - val_loss: 0.2741 - val_accuracy: 0.8979
Epoch 5/10
243/243 [==============================] - 8s 35ms/step - loss: 0.0361 - accuracy: 0.9883 - val_loss: 0.3375 - val_accuracy: 0.9034
Epoch 6/10
243/243 [==============================] - 8s 34ms/step - loss: 0.0220 - accuracy: 0.9929 - val_loss: 0.4420 - val_accuracy: 0.9045
Epoch 7/10
243/243 [==============================] - 8s 34ms/step - loss: 0.0132 - accuracy: 0.9963 - val_loss: 0.3943 - val_accuracy: 0.8

In [28]:
#train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)
train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)
#train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Epoch 1/50
243/243 [==============================] - 8s 33ms/step - loss: 0.0046 - accuracy: 0.9954 - val_loss: 0.0833 - val_accuracy: 0.9027
Epoch 2/50
243/243 [==============================] - 8s 32ms/step - loss: 0.0045 - accuracy: 0.9956 - val_loss: 0.0820 - val_accuracy: 0.9067
Epoch 3/50
243/243 [==============================] - 8s 34ms/step - loss: 0.0048 - accuracy: 0.9952 - val_loss: 0.0889 - val_accuracy: 0.9034
Epoch 4/50
243/243 [==============================] - 8s 34ms/step - loss: 0.0051 - accuracy: 0.9945 - val_loss: 0.0813 - val_accuracy: 0.9096
Epoch 5/50
243/243 [==============================] - 8s 35ms/step - loss: 0.0049 - accuracy: 0.9950 - val_loss: 0.0842 - val_accuracy: 0.9081
Epoch 6/50
243/243 [==============================] - 8s 33ms/step - loss: 0.0048 - accuracy: 0.9950 - val_loss: 0.0823 - val_accuracy: 0.9078
Epoch 7/50
243/243 [==============================] - 13s 52ms/step - loss: 0.0043 - accuracy: 0.9955 - val_loss: 0.0796 - val_accuracy: 0.907

In [28]:
#train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)
#train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=50,batch_size=64)
train_model=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=64)

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Epoch 1/100
243/243 [==============================] - 11s 36ms/step - loss: 0.0938 - accuracy: 0.8670 - val_loss: 0.0693 - val_accuracy: 0.9081
Epoch 2/100
243/243 [==============================] - 8s 34ms/step - loss: 0.0377 - accuracy: 0.9522 - val_loss: 0.0660 - val_accuracy: 0.9107
Epoch 3/100
243/243 [==============================] - 8s 33ms/step - loss: 0.0249 - accuracy: 0.9708 - val_loss: 0.0726 - val_accuracy: 0.9070
Epoch 4/100
243/243 [==============================] - 8s 33ms/step - loss: 0.0188 - accuracy: 0.9779 - val_loss: 0.0759 - val_accuracy: 0.9059
Epoch 5/100
243/243 [==============================] - 8s 33ms/step - loss: 0.0133 - accuracy: 0.9848 - val_loss: 0.0802 - val_accuracy: 0.9048
Epoch 6/100
243/243 [==============================] - 8s 34ms/step - loss: 0.0103 - accuracy: 0.9890 - val_loss: 0.0795 - val_accuracy: 0.9067
Epoch 7/100
243/243 [==============================] - 8s 33ms/step - loss: 0.0083 - accuracy: 0.9913 - val_loss: 0.0842 - val_accuracy